ARG NODE_VERSION=18

FROM node:${NODE_VERSION}-alpine as base

ENV NODE_ENV=development

WORKDIR /app

# Build
FROM base as build

COPY package.json yarn.lock ./
RUN yarn

# Run
FROM base

COPY --from=build /app/node_modules /app/node_modules

CMD [ "yarn", "dev"]