version: '3.8'
services:
  app:
    image: ghcr.io/fyargat/portfolio:latest
    ports:
      - target: 3000
        published: 3000
        mode: host
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
