version: '3.8'
services:
  app:
    image: ghcr.io/fyargat/portfolio:latest
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    env_file:
      - '.env'
    deploy:
      placement:
        constraints:
          - 'node.role==manager'

networks:
  default:
    name: portfolio_network
    external: true
