version: '3.8'
services:
  app:
    image: ghcr.io/fyargat/portfolio:latest
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1

networks:
  default:
    name: portfolio_network
    external: true
